/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MusicBall {
        /**
          * 自动播放
         */
        "autoPlay": boolean;
        /**
          * 动画速度
         */
        "duration": number;
        /**
          * 单曲循环
         */
        "loop": boolean;
        /**
          * music artist
         */
        "musicArtist": string;
        /**
          * music cover
         */
        "musicCover": string;
        /**
          * music title
         */
        "musicTitle": string;
        /**
          * music url
         */
        "musicUrl": string;
        /**
          * size of the ball
         */
        "size": number;
        /**
          * 主题颜色
         */
        "themeColor": string;
    }
}
declare global {
    interface HTMLMusicBallElement extends Components.MusicBall, HTMLStencilElement {
    }
    var HTMLMusicBallElement: {
        prototype: HTMLMusicBallElement;
        new (): HTMLMusicBallElement;
    };
    interface HTMLElementTagNameMap {
        "music-ball": HTMLMusicBallElement;
    }
}
declare namespace LocalJSX {
    interface MusicBall {
        /**
          * 自动播放
         */
        "autoPlay"?: boolean;
        /**
          * 动画速度
         */
        "duration"?: number;
        /**
          * 单曲循环
         */
        "loop"?: boolean;
        /**
          * music artist
         */
        "musicArtist"?: string;
        /**
          * music cover
         */
        "musicCover"?: string;
        /**
          * music title
         */
        "musicTitle"?: string;
        /**
          * music url
         */
        "musicUrl"?: string;
        /**
          * size of the ball
         */
        "size"?: number;
        /**
          * 主题颜色
         */
        "themeColor"?: string;
    }
    interface IntrinsicElements {
        "music-ball": MusicBall;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "music-ball": LocalJSX.MusicBall & JSXBase.HTMLAttributes<HTMLMusicBallElement>;
        }
    }
}
